name: Build and Push OASEES Images for Edge Devices

on:
  push:
    branches: ["main"]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        image:
          - name: oasees-agent

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./${{ matrix.image.name }}
          platforms: linux/amd64, linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image.name }}:latest