name: Build and Push OASEES Images to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        image:
          - name: solidity-ide
          - name: oasees-portal
          - name: cluster-backend
          - name: oasees-notebook
          - name: ml-base-image
          - name: oasees-agent

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./${{ matrix.image.name }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image.name }}:latest